Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2023
Var
// Seção de Declarações das variáveis 
C,F:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Digite o seu valor em Celsius")
 leia(C)
 F <- (C/5)*9+32
 Escreval(F)

Fimalgoritmo