Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2023
Var
// Seção de Declarações das variáveis 
X:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Escreve um numero ae")
 Leia(X)
 X<- X-1
 Escreva("O Antecessor é",X)
Fimalgoritmo